export const students=[
    {
        id:1,
        name:"Basic Electronics Lab",
        image:"",
        software:"LTSpice,Proteus",
        hardware:"Power supply, multimeters, oscilloscopes, function generators, breadboards, and various electronic components such as resistors, capacitors, and transistors.",
        about:"A basic electronics lab typically includes equipment such as power supplies, multimeters, oscilloscopes, and function generators. It is used to teach the fundamental principles of electronics, including circuit design, analysis, and troubleshooting. Students typically perform experiments to learn about resistors, capacitors, diodes, transistors, and op-amps.",  
    },
    {
        id:2,
        name:"Analog Electronics Lab",
        image:"",
        software:"LTSpice, CircuitMaker, PSpice, or Multisim",
        hardware:"Oscilloscopes, Function generators, Power supplies, Electronic components, Breadboards, Signal generators, Spectrum analyzers",
        about:"An analog electronics lab focuses on the study of circuits that process continuous signals. It typically includes equipment such as oscilloscopes, function generators, power supplies, and various electronic components. Students perform experiments to learn about amplifiers, filters, oscillators, and other analog circuits.",  
    },
    {
        id:3,
        name:"Digital Electronics Lab",
        image:"",
        software:"Tinkercad",
        hardware:"Breadboards and jumper wires, Digital multimeters, Oscilloscopes, Logic analyzers, Integrated circuits such as logic gates, flip-flops, counters, and registers, Microcontrollers or development boards like Arduino or Raspberry Pi, Field-Programmable Gate Arrays (FPGAs)",
        about:"Digital Electronics Lab is a practical course focused on designing, building and testing digital circuits using integrated circuits and electronic components. Students learn how to use tools such as logic analyzers, breadboards, and oscilloscopes to implement digital logic gates, flip-flops, counters, and registers. The lab aims to provide hands-on experience in digital circuit design and troubleshooting.",  
    },
    {
        id:4,
        name:"Digital Signal Processing Lab",
        image:"",
        software:"MATLAB, Simulink, LabVIEW",
        hardware:"Computers, microcontrollers, digital signal processors, analog-to-digital converters, digital-to-analog converters, oscilloscopes, function generators, and signal analyzers",
        about:"The Digital Signal Processing (DSP) Lab is a specialized facility for analyzing, processing, and manipulating digital signals using various software tools and hardware devices. It is commonly used in fields such as telecommunications, audio processing, image processing, and control systems. The lab provides hands-on experience in implementing DSP algorithms and techniques on real-world data.",  
    },
    {
        id:5,
        name:"Communication Lab",
        image:"",
        software:"MATLAB, Simulink, OptiSystem, Zemax",
        hardware:"Optical Communication Kits, Radar Test Kits, Satellite Test kits",
        about:"The Communication lab is a specialized facility that provides a controlled environment for conducting experiments, research, and development of radio frequency communication technologies used in RADAR and satellite systems. The lab features state-of-the-art equipment, such as signal generators, power amplifiers, antennas, and spectrum analyzers, for generating and measuring RF signals",  
    },
    {
        id:6,
        name:"VLSI Lab",
        image:"",
        software:"SPICE (Simulation Program with Integrated Circuit Emphasis), VHDL (VHSIC Hardware Description Language), Verilog, Synopsys and Xilinx CPLD/FPGA Boards",
        hardware:"Oscilloscopes, logic analyzers, and probe stations.",
        about:"A VLSI (Very Large-Scale Integration) lab is a facility equipped with tools and software for designing, fabricating, and testing integrated circuits with millions of transistors on a single chip. These labs typically include cleanrooms, photolithography equipment, semiconductor process tools, and measurement instruments to develop and verify chip designs.",  
    },
    {
        id:7,
        name:"Microwave Lab",
        image:"",
        software:"Ansoft HFSS, Keysight ADS, CST Studio Suite and MATLAB",
        hardware:"microwave signal generators, spectrum analyzers, network analyzers, power meters, oscilloscopes, and antennas",
        about:"A microwave lab is a facility equipped with instruments and devices to measure, manipulate and study electromagnetic waves in the microwave frequency range. These labs are used for research and development of microwave communication systems, radar, microwave heating, and other applications in electronics and telecommunications.",  
    },
    {
        id:8,
        name:"Microprocessor and Microcontroller Lab",
        image:"",
        software:"Keil MDK",
        hardware:"8085, 8086 and 8051 Trainer Kits.",
        about:"The Microprocessor and Microcontroller Lab is a facility for students and researchers to study and experiment with microprocessors and microcontrollers, which are the building blocks of modern computer systems. It provides hands-on experience in programming, interfacing, and controlling various devices and sensors using microprocessors and microcontrollers.",  
    },
];